module.exports = {
  preset: "@vue/cli-plugin-unit-jest",
  collectCoverageFrom: [
    "src/**/*.{js}",
    "src/**/index.js",
    "!src/**/*.test.{js}",
    "!src/**/*.tool.{js}",
  ],
  coverageThreshold: {
    global: {
      branches: 90,
      functions: 95,
      lines: 95,
      statements: 95,
    },
  },
  expand: true,
  displayName: {
    name: "vue3-extended-multiselect",
    color: "bgGreen",
  },
  extraGlobals: [],
  globals: {
    OPTIONS: [
      { label: "First Option", customLabel: "First Option Custom Label" },
      { label: "Second Option" },
      { label: "Third Option", searchByField: "First" },
      126,
      null,
    ],
    INPUT_ID: "vue3-extended-multiselect-input-1",
    SEARCH_VALUE: "Search for options",
    SEARCH_VALUE_WITH_RESULTS: "First",
    MORE_THAN_LIMIT: "You have to select no more than one option",
    LESS_THAN_LIMIT: "You have to select at least two options",
  },
  injectGlobals: true,
  moduleFileExtensions: ["js", "ts", "json", "mjs", "node", "vue"],
  moduleNameMapper: {
    "\\.svg$": "<rootDir>/tests/tools/stubs.tool",
    "\\.scss$": "identity-obj-proxy",
  },
  resetModules: true,
  resetMocks: true,
  rootDir: "./",
  setupFiles: ["<rootDir>/tests/tools/mocks.tool.js"],
  slowTestThreshold: 20,
  testEnvironment: "jsdom",
  testLocationInResults: true,
  testMatch: ["**/tests/**/*.[jt]s?(x)", "**/?(*.)+(spec|test).[tj]s?(x)"],
  testPathIgnorePatterns: ["tests/tools/*"],
  timers: "real",
  transform: {
    "^.+\\.vue$": "@vue/vue3-jest",
  },
  transformIgnorePatterns: ["<rootDir>/node_modules/*"],
};
