name: CI

on:
  push:
    branches: [master, feat/*, fix/*, docs/*, chore/*]
  pull_request:
    branches: [master]

jobs:
  test:
    name: Test Suite
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: ["20"]
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: "npm"

      - name: Install dependencies
        run: npm ci --include=dev

      - name: Run unit tests
        run: npm test -- --coverage

      - name: Upload coverage
        uses: codecov/codecov-action@v3

      - name: Build package
        run: npm run build

      - name: Run bundlewatch
        if: github.event_name != 'pull_request'
        run: |
          if [ -f "bundlewatch.config.json" ]; then
            echo "Installing latest bundlewatch..."
            npm install bundlewatch@latest glob@latest --no-save --no-audit
            echo "Running bundlewatch..."
            npx bundlewatch --config bundlewatch.config.json
          else
            echo "No bundlewatch.config.json found — skipping size checks"
          fi

  lint:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - run: npm ci
      - run: npm run lint
